### ISSUE TITLE
Establishing testing strategy [Component Library]

### ISSUE THREAD

**Issue by DanielvanVliet** [Gemeente-DenHaag/denhaag-component-library#107]
**A testing strategy should be defined for the components**

## Details
Currently, no decisions have been made about testing. Now that we start to style the components, we should decide how we test (what kind of tests, which frameworks and a targeted coverage) them to ensure it remains functional after a change has been made and to ensure a newly added piece of functionality works as expected.

If the functionality that needs to be tested at the moment we start working on this story is still limited, apply the testing strategy to all current code where it's deemed necessary. If the amount of untested code is significant, a separate story should be made to create the tests.

## Acceptance criteria
- [x] Desired types of tests are determined and discussed (smoke, functional, unit)
- [x] Research how to test a11y.
- [x] Suggestions or decisions for frameworks are determined
- [x] Write example test
- [x] Testing guidelines are documented in README.md

**Comment by Test-Automation-Engineer** [comment]
I would like to get involved with this story @bddjong @joostvanviegen @DanielvanVliet 
Please setup a meeting so we can discuss your thoughts.

**Comment by bddjong** [comment]
@mjcarsjens We've discussed whether or not we should explicitly document the manual testing that's required for accessibility, since 100% a11y automated coverage isn't possible. Do you think we should document specific things to test manually? It might take a while to investigate what wcag guidelines arent covered by the automated tests.
