### ISSUE TITLE
Design: Divider

### ISSUE THREAD

**Issue by GewoonMaarten** [Gemeente-DenHaag/denhaag-component-library#63]
The Divider component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1596%3A83) design.

## Acceptance criteria
**Variants implemented**
- [x] Horizontal
- [x] Vertical

**Requirements**
- [x] Width is always the full width of the container
- [x] [Alignment](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1596%3A83)  requirements are met
- [x] Classes use the BEM naming convention
- [ ] Design tokens are identified > proposed > implemented
- [x] Only the `props` and possible values for these `props` which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.

**Comment by ogjtech** [comment]
> Only the props and possible values for these props which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.

@Gemeente-DenHaag/mdh-rysst something to keep in mind for all of the designs about this specific requirement. While we may not want to expose every property of the underlying MUI component, it is important to remember that some MUI components do not work (as expected) when specific properties are not supplied. In this case, we should either define a standard property for this in the wrapper and pass it directly to the `MaterialX` component.

In my opinion, we should just expose as much as possible to allow for flexibility right away instead of adding later, but for our scope I would keep this in mind.

**Comment by Robbert** [comment]
This component is an implementation of the Separator component in NL Design System: nl-design-system/backlog#119
